config/routes.rb
Rails.application.routes.draw do

  # -------- Root and Dashboard

  get '/'          => redirect('/dashboard')
  get '/dashboard' => 'dashboard#index'

  # -------- Sessions

  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # -------- Unsorted

  get '/tareas'           => 'tasks#index'   , as: :tasks
  get '/tareas/:type'     => 'tasks#index'   , as: :tasks_type
  get '/tareas/detalle/:id'   => 'tasks#show', as: :task

  get '/hallazgos'    => 'findings#index'
  get 'hallazgos/:id' => 'findings#show', as: :finding

  # -------- Betterment

  # -- Audit Programs

  get '/mejora/auditoria'            => 'audit_programs#index', as: :audit_programs
  get '/mejora/auditoria/nuevo'      => 'audit_programs#new',   as: :new_audit_program
  get '/mejora/auditoria/:id'        => 'audit_programs#show',  as: :audit_program
  get '/mejora/auditoria/:id/editar' => 'audit_programs#edit',  as: :edit_audit_program

  post '/mejora/auditoria/nuevo' => 'audit_programs#create'

  # --- Audits

  get '/mejoras/auditoria/:program_id'            => 'audits#index', as: :audits
  get '/mejoras/auditoria/:program_id/nuevo'      => 'audits#new',   as: :new_audit
  get '/mejoras/auditoria/:program_id/:id'        => 'audits#show',  as: :audit
  get '/mejoras/auditoria/:program_id/:id/editar' => 'audits#edit',  as: :edit_audit

  post  '/mejoras/auditoria/:program_id/nuevo'      => 'audits#create'
  patch '/mejoras/auditoria/:program_id/:id/editar' => 'audits#update'


  #get '/analisis/indicadores/:indicator_id/nueva'      => 'indicator_measurements#new' ,
  #    as: :new_indicator_measurement
  #get '/analisis/indicadores/:indicator_id/:id/editar' => 'indicator_measurements#edit',
  #    as: :edit_indicator_measurement

  #patch '/analisis/indicadores/:id/editar'       => 'indicators#update'
  #patch '/analisis/indicadores/edit-attachments' => 'indicators#edit_attachments'

  #post  '/analisis/indicadores/:indicator_id/nueva'      => 'indicator_measurements#create'
  #patch '/analisis/indicadores/:indicator_id/:id/editar' => 'indicator_measurements#update'

  # -------- Employees

  # Employees Files
  get '/personas/fichas'            => 'users#index', as: :users
  get '/personas/fichas/nuevo'      => 'users#new',   as: :new_user
  get '/personas/fichas/:id'        => 'users#show',  as: :user
  get '/personas/fichas/:id/editar' => 'users#edit',  as: :edit_user

  post  '/personas/fichas/nuevo'            => 'users#create'
  patch '/personas/fichas/:id/editar'       => 'users#update'
  patch '/personas/fichas/edit-attachments' => 'users#edit_attachments'


  # Organization Chart
  get '/personas/organigrama'            => 'positions#index', as: :positions
  get '/personas/organigrama/nueva'      => 'positions#new',   as: :new_position
  get '/personas/organigrama/:id'        => 'positions#show',  as: :position
  get '/personas/organigrama/:id/editar' => 'positions#edit',  as: :edit_position

  post  '/personas/organigrama/nueva'             => 'positions#create'
  patch '/personas/organigrama/:id/editar'        => 'positions#update'
  patch '/personas/:organigrama/edit-attachments' => 'positions#edit_attachments'

  # Competencies & Performance evaluations, Climate
  get '/personas/evaluaciones/clima'       => 'users#work_environment' # ??
  get '/personas/evaluaciones/:type'       => 'employee_evaluations#index', as: :employee_evaluations
  get '/personas/evaluaciones/:type/nuevo' => 'employee_evaluations#new',   as: :new_employee_evaluation
  get '/personas/evaluaciones/:type/:id'   => 'employee_evaluations#show',  as: :employee_evaluation

  post '/personas/evaluaciones/:type/nuevo' => 'employee_evaluations#create'

  # -------- Clients

  # Clients Files
  get '/clientes/fichas'            => 'clients#index', as: :clients
  get '/clientes/fichas/nuevo'      => 'clients#new',   as: :new_client
  get '/clientes/fichas/:id'        => 'clients#show',  as: :client
  get '/clientes/fichas/:id/editar' => 'clients#edit',  as: :edit_client

  post  '/clientes/fichas/nuevo'            => 'clients#create'
  patch '/clientes/fichas/:id/editar'       => 'clients#update'
  patch '/clientes/fichas/edit-attachments' => 'clients#edit_attachments'


  # Client Types
  get '/clientes/tipos'            => 'client_types#index', as: :client_types
  get '/clientes/tipos/nuevo'      => 'client_types#new',   as: :new_client_type
  get '/clientes/tipos/:id'        => 'client_types#show',  as: :client_type
  get '/clientes/tipos/:id/editar' => 'client_types#edit',  as: :edit_client_type

  post  '/clientes/tipos/nuevo'            => 'client_types#create'
  patch '/clientes/tipos/:id/editar'       => 'client_types#update'
  patch '/clientes/tipos/edit-attachments' => 'client_types#edit_attachments'


  # Client Satisfaction (??)
  get '/clientes/satisfaccion' => 'clients#satisfaction' # ??

  # -------- Providers

  # Providers Files
  get '/proveedores/fichas'            => 'providers#index', as: :providers
  get '/proveedores/fichas/nuevo'      => 'providers#new',   as: :new_provider
  get '/proveedores/fichas/:id'        => 'providers#show',  as: :provider
  get '/proveedores/fichas/:id/editar' => 'providers#edit',  as: :edit_provider

  post  '/proveedores/fichas/nuevo'            => 'providers#create'
  patch '/proveedores/fichas/:id/editar'       => 'providers#update'
  patch '/proveedores/fichas/edit-attachments' => 'providers#edit_attachments'


  # Provider Types
  get '/proveedores/tipos'            => 'provider_types#index', as: :provider_types
  get '/proveedores/tipos/nuevo'      => 'provider_types#new',   as: :new_provider_type
  get '/proveedores/tipos/:id'        => 'provider_types#show',  as: :provider_type
  get '/proveedores/tipos/:id/editar' => 'provider_types#edit',  as: :edit_provider_type

  post  '/proveedores/tipos/nuevo'            => 'provider_types#create'
  patch '/proveedores/tipos/:id/editar'       => 'provider_types#update'
  patch '/proveedores/tipos/edit-attachments' => 'provider_types#edit_attachments'


  # Competencies & Performance evaluations
  get '/proveedores/evaluaciones/:type'       => 'provider_evaluations#index', as: :provider_evaluations
  get '/proveedores/evaluaciones/:type/nuevo' => 'provider_evaluations#new',   as: :new_provider_evaluation
  get '/proveedores/evaluaciones/:type/:id'   => 'provider_evaluations#show',  as: :provider_evaluation

  post '/proveedores/evaluaciones/:type/nuevo' => 'provider_evaluations#create'

  # -------- Analysis: Indicators

  get '/analisis/indicadores'            => 'indicators#index', as: :indicators
  get '/analisis/indicadores/nuevo'      => 'indicators#new',   as: :new_indicator
  get '/analisis/indicadores/:id'        => 'indicators#show',  as: :indicator
  get '/analisis/indicadores/:id/editar' => 'indicators#edit',  as: :edit_indicator

  get '/analisis/indicadores/:indicator_id/nueva'      => 'indicator_measurements#new' ,
      as: :new_indicator_measurement
  get '/analisis/indicadores/:indicator_id/:id/editar' => 'indicator_measurements#edit',
      as: :edit_indicator_measurement

  post  '/analisis/indicadores/nuevo'            => 'indicators#create'
  patch '/analisis/indicadores/:id/editar'       => 'indicators#update'
  patch '/analisis/indicadores/edit-attachments' => 'indicators#edit_attachments'

  post  '/analisis/indicadores/:indicator_id/nueva'      => 'indicator_measurements#create'
  patch '/analisis/indicadores/:indicator_id/:id/editar' => 'indicator_measurements#update'

  # -------- Assets

  get '/activos/:job_type'            => 'business_assets#index', as: :business_assets
  get '/activos/:job_type/nuevo'      => 'business_assets#new',   as: :new_business_asset
  get '/activos/:job_type/:id'        => 'business_assets#show',  as: :business_asset
  get '/activos/:job_type/:id/editar' => 'business_assets#edit',  as: :edit_business_asset

  get '/activos/:job_type/:asset_id/nuevo'       => 'business_asset_jobs#new',  as: :new_asset_job
  get '/activos/:job_type/:asset_id/:id/editar'  => 'business_asset_jobs#edit', as: :edit_asset_job

  post '/activos/nuevo-tipo' => 'business_assets#create_type',
       as: :new_business_asset_type

  post  '/activos/:job_type/nuevo'            => 'business_assets#create'
  patch '/activos/:job_type/:id/editar'       => 'business_assets#update'
  patch '/activos/:job_type/edit-attachments' =>  'business_assets#edit_attachments'


  post  '/activos/:job_type/:asset_id/nuevo'       => 'business_asset_jobs#create'
  patch '/activos/:job_type/:asset_id/:id/editar'  => 'business_asset_jobs#update'

  # -------- Planning

  get '/planificacion'            => 'plannings#index', as: :plannings
  get '/planificacion/nueva'      => 'plannings#new'  , as: :new_planning
  get '/planificacion/:id'        => 'plannings#show' , as: :planning
  get '/planificacion/:id/editar' => 'plannings#edit' , as: :edit_planning

  get '/planificacion/:plan_id/nueva'      => 'planning_activities#new',  as: :new_planning_activity
  get '/planificacion/:plan_id/:id/editar' => 'planning_activities#edit', as: :edit_planning_activity

  post  '/planificacion/nueva'            => 'plannings#create'
  patch '/planificacion/:id/editar'       => 'plannings#update'
  patch '/planificacion/edit-attachments' => 'plannings#edit_attachments'


  post  '/planificacion/:plan_id/nueva'      => 'planning_activities#create'
  patch '/planificacion/:plan_id/:id/editar' => 'planning_activities#update'

  # -------- Documents

  post '/documentos/reglas/nuevo' => 'rules#create', as: :new_rule

  # -- Uploads
  get '/documentos/archivos'       => 'uploaded_files#index', as: :uploaded_files
  get '/documentos/archivos/nuevo' => 'uploaded_files#new',   as: :new_uploaded_file
  get '/documentos/archivos/:id'   => 'uploaded_files#show',  as: :uploaded_file

  post '/documentos/archivos/nuevo' => 'uploaded_files#create'

  # -- Minutes

app/controllers/provider_types_controller.rb
class ProviderTypesController < ApplicationController
  def index
    render layout: 'table'
  end

  def show
    @type = ProviderType.find(params[:id])
    redirect_to_dashboard unless @type

    render layout: 'show'
  end

  def new
    render layout: 'form'
  end

  def edit
    @type = ProviderType.find(params[:id])
    redirect_to_dashboard unless @type

    render layout: 'form'
  end

  def create
    type = ProviderType.create!(provider_type_fields)
    log_created(type)

    create_references(type, references_unsafe_hash)
    add_attachments(type, params.dig(:type, :attachments))

    redirect_to type
  end

  def update
    type = ProviderType.find(params[:id])
    redirect_to_dashboard && return unless type

    type.update!(provider_type_fields)
    log_edited(type)

    create_references(type, references_unsafe_hash)

    redirect_to type
  end

  def edit_attachments
    type = ProviderType.find(params.dig(:attachments, :element_id))
    return unless type

    additions = params.dig(:attachments, :additions)
    removal_ids = params.dig(:attachments, :removal_ids)

    add_attachments(type, additions) if additions
    remove_attachments(type.class.name, type, removal_ids) if
        removal_ids

    redirect_to type
  end

  private

  def provider_type_fields
    fields = params.require(:type)

    fields.permit(
      :name, :description,
      competency_ids: [], performance_ids: [],
      provider_ids: []
    )
  end
end

app/views/provider_types/edit.html.erb
<%= form_for(@type, as: :type,
             url: edit_provider_type_path(@type), method: :patch) do |f| %>

    <section class="page-content">
      <div class="page-content-inner">

        <div class="panel">
          <%= render partial: 'referables/references_nav' %>

          <div class="row form-group margin-left-30 margin-right-20">
            <div class="col-lg-1">
              <label class="form-control-label">
                Nombre
              </label>
            </div>
            <div class="col-lg-3">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="col-lg-1">
              <label class="form-control-label">
                Descripción
              </label>
            </div>
            <div class="col-lg-7">
              <%= f.text_field :description, class: 'form-control' %>
            </div>
          </div>

          <div class="row margin-30">
            <div class="col-lg-2" style="text-align: center; vertical-align: middle">
              <h5 class="margin-0">
                <a href="javascript:openProvidersModal()">
                  Proveedores:
                </a>
              </h5>
            </div>
            <div class="col-lg-6" id="providers-in"></div>
          </div>

          <div class="row margin-left-30 margin-right-30">
            <div class="col-lg-6" id="competencies-in">
              <h6>
                <a href="javascript:openCompetenciesModal()">
                  Competencias
                </a>
              </h6>
            </div>
            <div class="col-lg-6" id="performances-in">
              <h6>
                <a href="javascript:openPerformancesModal()">
                  Desempeño Esperado
                </a>
              </h6>
            </div>
          </div>

          <div class="row form-group" style="margin: 30px 10px;height:400px">
            <%= f.text_area :comments, class: 'form-control', data: {provider: 'summernote'} %>
          </div>

          <div style="margin: 0 30px 10px 30px">
            <%= render partial: 'referables/show_all_for',
                       locals: {element: @type, form_format: true} %>
          </div>

        </div>
      </div>
    </section>

    <!-- Confirmation modal -->
    <div id="confirmation-modal" class="modal fade modal-size-large" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content" id="confirmation-modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="confirmation-modal-title">Está Seguro?</h4>
          </div>

          <div class="modal-body" id="confirmation-modal-body">
            <%= text_area :log, :body, class: 'form-control height-150' %>
          </div>

          <div class="modal-footer">
            <div class="row">
              <div class="col-md-6 text-left">
                <button class="btn btn-danger width-150 height-50" data-dismiss="modal">Cancelar</button>
              </div>
              <div class="text-right col-md-6">
                <%= f.submit 'Ingresar', class: 'btn btn-primary width-150 height-50' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

<%= content_for :scripts do %>
    <script>
        function providersElementGenerator(target, klass, id, name) {
            target.append(
                '<div id="reference-' + id + '" style="display:inline">\n' +

                '<input class="form-control-hidden" type="hidden" ' +
                'name="type[provider_ids][]" id="type_provider_ids" ' +
                'value="' + id + '">\n' + (target.is(':empty') ? '' : ', ') + name +
                '</div>'
            );
        }

        function competencyElementGenerator(target, klass, id, name) {
            target.append(
                '<div id="reference-' + id + '">\n' +

                '<input class="form-control-hidden" type="hidden" ' +
                'name="type[competency_ids][]" id="type_competency_ids" ' +
                'value="' + id + '">\n' +

                '<input class="form-control" readonly="readonly" type="text" ' +
                'name="extra[competency_names][]" id="extra_competency_names" ' +
                'value="' + name + '">\n' +

                '</div>'
            );
        }
        function performanceElementGenerator(target, klass, id, name) {
            target.append(
                '<div id="reference-' + id + '">\n' +

                '<input class="form-control-hidden" type="hidden" ' +
                'name="type[performance_ids][]" id="type_performance_ids" ' +
                'value="' + id + '">\n' +

                '<input class="form-control" readonly="readonly" type="text" ' +
                'name="extra[performance_names][]" id="extra_performance_names" ' +
                'value="' + name + '">\n' +

                '</div>'
            );
        }

        function openProvidersModal() {
            setOptions('Person::Provider', 'Proveedores', true, 'providers', $('#providers-in'));
            setElementGenerator(providersElementGenerator);

            renderAndShowReferencesModal();
        }

        function openCompetenciesModal() {
            setOptions('Qualification', 'Competencias', true, 'type_competencies', $('#competencies-in'));
            setElementGenerator(competencyElementGenerator);

            renderAndShowReferencesModal('1');
        }

        function openPerformancesModal() {
            setOptions('Qualification', 'Desempeños', true, 'type_performances', $('#performances-in'));
            setElementGenerator(performanceElementGenerator);

            renderAndShowReferencesModal('2');
        }

        $(document).ready(function () {
            // Load lists
            setList('providers', <%= raw(@type.provider_ids.map { |id| id.to_s }.to_s) %>, null);

            // Show all
            <% @type.providers.each do |provider| %>
                providersElementGenerator($('#providers-in'), 'providers',
                    '<%= provider.id.to_s %>', '<%= provider.full_name %>');
            <% end %>

            <% if @type.competency_ids? %>
                setList('type_competencies', <%= raw @type.competency_ids %>, null);

                <% @type.competency_ids.each do |id| %>
                    <% competency = Qualification.find(id) %>
                    competencyElementGenerator($('#competencies-in'), 'type_competencies',
                        '<%= id.to_s %>', '<%= competency.phrase %>');
                <% end %>
            <% end %>

            <% if @type.performance_ids? %>
                setList('type_performances', <%= raw @type.performance_ids %>, null);

                <% @type.performance_ids.each do |id| %>
                    <% performance = Qualification.find(id) %>
                    performanceElementGenerator($('#performances-in'), 'type_performances',
                        '<%= id.to_s %>', '<%= performance.phrase %>');
                <% end %>
            <% end %>
        });
    </script>
<% end %>

<%= content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to 'Proveedores: Tipos', client_types_path %>
        </li>
        <li>
          <%= link_to @type.number, provider_type_path(@type) %>
        </li>
        <li>
          <span>
            Nuevo
          </span>
        </li>
      </ul>
    </div>
<% end %>

app/views/provider_types/index.html.erb
<% content_for :before_table do %>
<% end %>

<% content_for :table_name_active do %>
    Activos
<% end %>

<% content_for :table_headers do %>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
    </tr>
<% end %>

<% content_for :table_body do %>
    <% provider_types = ProviderType.all %>

    <% if provider_types.size != 0 %>
        <% provider_types.each do |type| %>
            <tr data-href="<%= provider_type_path(type) %>">
              <td>
                <%= type.name %>
              </td>
              <td>
                <%= type.description %>
              </td>
            </tr>
        <% end %>
    <% else %>
        <tr>
          <td colspan="2"> No se encontraron tipos de proveedores.</td>
        </tr>
    <% end %>
<% end %>


<% content_for :menu do %>
    <div class="dropdown">
      <%= link_to new_provider_type_path, class: 'dropdown-inline-button' do %>
          <i class="dropdown-inline-button-icon icmn-file-plus"></i>
          Nuevo
      <% end %>
    </div>
<% end %>

<% content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
        <span>
          Proveedores: Tipos
        </span>
        </li>
      </ul>
    </div>
<% end %>

app/views/provider_types/new.html.erb
<%= form_for(:type, url: new_provider_type_path) do |f| %>

    <section class="page-content">
      <div class="page-content-inner">

        <div class="panel">
          <%= render partial: 'referables/references_nav' %>

          <div class="row form-group margin-left-30 margin-right-20">
            <div class="col-lg-1">
              <label class="form-control-label">
                Nombre
              </label>
            </div>
            <div class="col-lg-3">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="col-lg-1">
              <label class="form-control-label">
                Descripción
              </label>
            </div>
            <div class="col-lg-7">
              <%= f.text_field :description, class: 'form-control' %>
            </div>
          </div>

          <div class="row margin-30">
            <div class="col-lg-2" style="text-align: center; vertical-align: middle">
              <h5 class="margin-0">
                <a href="javascript:openProvidersModal()">
                  Proveedores:
                </a>
              </h5>
            </div>
            <div class="col-lg-6" id="providers-in"></div>
          </div>

          <div class="row margin-left-30 margin-right-30">
            <div class="col-lg-6" id="competencies-in">
              <h6>
                <a href="javascript:openCompetenciesModal()">
                  Competencias
                </a>
              </h6>
            </div>
            <div class="col-lg-6" id="performances-in">
              <h6>
                <a href="javascript:openPerformancesModal()">
                  Desempeño Esperado
                </a>
              </h6>
            </div>
          </div>

          <div style="margin:50px 50px 0 50px">
            <%= f.file_field :attachments, class: 'dropify', multiple: true,
                             data: {height: '90px', width: '100%'} %>
          </div>

          <div class="row form-group" style="margin: 30px 10px;height:400px">
            <%= f.text_area :comments, class: 'form-control', data: {provider: 'summernote'} %>
          </div>

          <div id="references-container" style="margin: 0 30px 10px 30px">
            <h6>Referencias</h6>
          </div>

        </div>
      </div>
    </section>

    <!-- Confirmation modal -->
    <div id="confirmation-modal" class="modal fade modal-size-large" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content" id="confirmation-modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="confirmation-modal-title">Está Seguro?</h4>
          </div>

          <div class="modal-body" id="confirmation-modal-body">
            <%= text_area :log, :body, class: 'form-control height-150' %>
          </div>

          <div class="modal-footer">
            <div class="row">
              <div class="col-md-6 text-left">
                <button class="btn btn-danger width-150 height-50" data-dismiss="modal">Cancelar</button>
              </div>
              <div class="text-right col-md-6">
                <%= f.submit 'Ingresar', class: 'btn btn-primary width-150 height-50' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

<%= content_for :scripts do %>
    <script>
        function providersElementGenerator(target, klass, id, name) {
            target.append(
                '<div id="reference-' + id + '" style="display:inline">\n' +

                '<input class="form-control-hidden" type="hidden" ' +
                'name="type[provider_ids][]" id="type_provider_ids" ' +
                'value="' + id + '">\n' + (target.is(':empty') ? '' : ', ') + name +
                '</div>'
            );
        }

        function competencyElementGenerator(target, klass, id, name) {
            target.append(
                '<div id="reference-' + id + '">\n' +

                '<input class="form-control-hidden" type="hidden" ' +
                'name="type[competency_ids][]" id="type_competency_ids" ' +
                'value="' + id + '">\n' +

                '<input class="form-control" readonly="readonly" type="text" ' +
                'name="extra[competency_names][]" id="extra_competency_names" ' +
                'value="' + name + '">\n' +

                '</div>'
            );
        }
        function performanceElementGenerator(target, klass, id, name) {
            target.append(
                '<div id="reference-' + id + '">\n' +

                '<input class="form-control-hidden" type="hidden" ' +
                'name="type[performance_ids][]" id="type_performance_ids" ' +
                'value="' + id + '">\n' +

                '<input class="form-control" readonly="readonly" type="text" ' +
                'name="extra[performance_names][]" id="extra_performance_names" ' +
                'value="' + name + '">\n' +

                '</div>'
            );
        }

        function openProvidersModal() {
            setOptions('Person::Provider', 'Proveedores', true, 'providers', $('#providers-in'));
            setElementGenerator(providersElementGenerator);

            renderAndShowReferencesModal();
        }

        function openCompetenciesModal() {
            setOptions('Qualification', 'Competencias', true, 'type_competencies', $('#competencies-in'));
            setElementGenerator(competencyElementGenerator);

            renderAndShowReferencesModal('1');
        }

        function openPerformancesModal() {
            setOptions('Qualification', 'Desempeños', true, 'type_performances', $('#performances-in'));
            setElementGenerator(performanceElementGenerator);

            renderAndShowReferencesModal('2');
        }
    </script>
<% end %>

<%= content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to 'Proveedores: Tipos', provider_types_path %>
        </li>
        <li>
          <span>
            Nuevo
          </span>
        </li>
      </ul>
    </div>
<% end %>

app/views/provider_types/show.html.erb
<%= content_for :heading_main do %>
<% end %>

<%# Populate all 3 columns of the view with keys & their values %>

<%= content_for :main_col_1 do %>
    <div class="row">
      <div class="col-lg-4 show-label">Nombre:</div>
      <div class="col-lg-8">
        <%= @type.name %>
      </div>
    </div>
<% end %>

<%= content_for :main_col_2 do %>
    <div class="row">
      <div class="col-lg-4 show-label">Descripción:</div>
      <div class="col-lg-8">
        <%= @type.description %>
      </div>
    </div>
<% end %>

<%= content_for :main_col_3 do %>
<% end %>

<%= content_for :extra do %>
    <div class="row margin-top-10">
      <%if @type.providers? %>
          <div class="col-lg-2">
            <div class="panel">
              <div class="panel-heading">
                <h5>
                  Proveedores
                </h5>
              </div>
              <div class="panel-body" style="height: 100px; overflow: auto">
                <% @type.providers.each do |provider| %>
                    <%= link_to provider.full_name, provider %>
                    <br>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>

      <% if @type.competency_ids? %>
          <div class="col-lg-5">
            <div class="panel">
              <div class="panel-heading">
                <h5>
                  Competencias
                </h5>
              </div>
              <div class="panel-body" style="height: 100px; overflow: auto">
                <% @type.competency_ids.each do |competency_id| %>
                    <%= Qualification.find(competency_id).phrase %>
                    <br>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
      <% if @type.performance_ids? %>
          <div class="col-lg-5">
            <div class="panel">
              <div class="panel-heading">
                <h5>
                  Desempeños
                </h5>
              </div>
              <div class="panel-body" style="height: 100px; overflow: auto">
                <% @type.performance_ids.each do |performance_id| %>
                    <%= Qualification.find(performance_id).phrase %>
                    <br>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
    </div>

    <% if @type.comments? %>
        <div class="panel">
          <div class="panel-heading">
            <h5>Descripción</h5>
          </div>
          <div class="margin-left-30 margin-bottom-30">
            <%= raw @type.comments %>
          </div>
        </div>
    <% end %>

    <div class="row is-flex">
      <div class="col-lg-5">
        <% if @type.attachment_ids? %>
            <div class="panel">
              <div class="panel-heading">
                <h5>Adjuntos</h5>
              </div>
              <%= render partial: 'uploaded_files/attachments_table',
                         locals: {element: @type} %>
            </div>
        <% end %>
      </div>
      <div class="col-lg-1"></div>
      <div class="col-lg-6">
        <% if @type.references? %>
            <div class="panel padding-bottom-25" style="height: 100%">
              <%= render partial: 'referables/show_all_for',
                         locals: {element: @type} %>
            </div>
        <% end %>
      </div>
    </div>
<% end %>

<%= content_for :menu do %>
    <div class="dropdown">
      <% history_content = "#{escape_javascript(render partial: 'log/modal', locals: {book: @type.log_book})}" %>
      <a href="javascript:void(0)" class="dropdown-inline-button" onclick="showHistory('<%= history_content %>')">
        <i class="dropdown-inline-button-icon icmn-history"></i>
        Bitácora
      </a>
    </div>

    <div class="dropdown">
      <%= link_to edit_provider_type_path(@type.id), class: 'dropdown-inline-button' do %>
          <i class="dropdown-inline-button-icon icmn-pencil"></i>
          Editar
      <% end %>
    </div>
<% end %>



<% content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to provider_types_path do %>
              Proveedores: Tipos
          <% end %>
        </li>
        <li>
          <span>
            <%= @type.number %>
          </span>
        </li>
      </ul>
    </div>
<% end %>