config/routes.rb
  post  '/planificacion/nueva'            => 'plannings#create'
  patch '/planificacion/:id/editar'       => 'plannings#update'
  patch '/planificacion/edit-attachments' => 'plannings#edit_attachments'


  post  '/planificacion/:plan_id/nueva'      => 'planning_activities#create'
  patch '/planificacion/:plan_id/:id/editar' => 'planning_activities#update'

  # -------- Documents

  post '/documentos/reglas/nuevo' => 'rules#create', as: :new_rule

  # -- Uploads
  get '/documentos/archivos'       => 'uploaded_files#index', as: :uploaded_files
  get '/documentos/archivos/nuevo' => 'uploaded_files#new',   as: :new_uploaded_file
  get '/documentos/archivos/:id'   => 'uploaded_files#show',  as: :uploaded_file

  post '/documentos/archivos/nuevo' => 'uploaded_files#create'

  # -- Minutes

  get '/documentos/actas'            => 'minutes_folders#index', as: :minutes_folders
  get '/documentos/actas/nuevo'      => 'minutes_folders#new',   as: :new_minutes_folder
  get '/documentos/actas/:id'        => 'minutes_folders#show',  as: :minutes_folder
  get '/documentos/actas/:id/editar' => 'minutes_folders#edit',  as: :edit_minutes_folder

  post  '/documentos/actas/nuevo'      => 'minutes_folders#create'
  patch '/documentos/actas/:id/editar' => 'minutes_folders#update'

  get '/documentos/actas/:folder_id/nueva' => 'minutes#new', as: :new_minute
  get '/documentos/actas/:folder_id/:id'   => 'minutes#edit', as: :edit_minute

  post  '/documentos/actas/:folder_id/nueva' => 'minutes#create'
  patch '/documentos/actas/:folder_id/:id'   => 'minutes#update'

  # -- Definitions

  get '/documentos/definiciones'            => 'definitions#index', as: :definitions
  get '/documentos/definiciones/nuevo'      => 'definitions#new',   as: :new_definition
  get '/documentos/definiciones/:id'        => 'definitions#show',  as: :definition
  get '/documentos/definiciones/:id/editar' => 'definitions#edit',  as: :edit_definition

  post  '/documentos/definiciones/nuevo'      => 'definitions#create'
  patch '/documentos/definiciones/:id/editar' => 'definitions#update'

  # -- Questionnaires

  get '/documentos/cuestionarios'            => 'questionnaires#index', as: :questionnaires
  get '/documentos/cuestionarios/nuevo'      => 'questionnaires#new',   as: :new_questionnaire
  get '/documentos/cuestionarios/:id'        => 'questionnaires#show',  as: :questionnaire
  get '/documentos/cuestionarios/:id/editar' => 'questionnaires#edit',  as: :edit_questionnaire

  get '/documentos/cuestionarios/:id/responder' => 'questionnaires#respond',
      as: :respond_questionnaire

  post  '/documentos/cuestionarios/nuevo'      => 'questionnaires#create'
  patch '/documentos/cuestionarios/:id/editar' => 'questionnaires#update'

  post '/documentos/cuestionarios/:id/responder' => 'questionnaires#process_response'

  # -------- Strategies: SWOT

  get '/estrategias/FODA'            => 'swot#index', as: :swot_index
  get '/estrategias/FODA/nuevo'      => 'swot#new',   as: :new_swot
  get '/estrategias/FODA/:id'        => 'swot#show',  as: :swot
  get '/estrategias/FODA/:id/editar' => 'swot#edit',  as: :edit_swot

  post  '/estrategias/FODA/nuevo'      => 'swot#create'
  patch '/estrategias/FODA/:id/editar' => 'swot#update'
  patch '/estrategias/FODA/edit-attachments' => 'swot#edit_attachments'

  get '/estrategias/FODA/:swot_id/revisiones/nueva' => 'swot_revisions#new',
      as: :new_swot_revision
  get '/estrategias/FODA/:swot_id/revisiones/:id'   => 'swot_revisions#edit',
      as: :edit_swot_revision

  post  '/estrategias/FODA/:swot_id/revisiones/nueva' => 'swot_revisions#create'
  patch '/estrategias/FODA/:swot_id/revisiones/:id'   => 'swot_revisions#update'

  # -------- Strategies: PESTE

  get '/estrategias/PESTA'            => 'peste#index', as: :peste_index
  get '/estrategias/PESTA/nuevo'      => 'peste#new',   as: :new_peste
  get '/estrategias/PESTA/:id'        => 'peste#show',  as: :peste
  get '/estrategias/PESTA/:id/editar' => 'peste#edit',  as: :edit_peste

  post  '/estrategias/PESTA/nuevo'            => 'peste#create'
  patch '/estrategias/PESTA/:id/editar'       => 'peste#update'
  patch '/estrategias/PESTA/edit-attachments' => 'peste#edit_attachments'

  get '/estrategias/PESTA/:peste_id/revisiones/nueva' => 'peste_revisions#new',
      as: :new_peste_revision
  get '/estrategias/PESTA/:peste_id/revisiones/:id'   => 'peste_revisions#edit',
      as: :edit_peste_revision

  post  '/estrategias/PESTA/:peste_id/revisiones/nueva' => 'peste_revisions#create'
  patch '/estrategias/PESTA/:peste_id/revisiones/:id'   => 'peste_revisions#update'

  # -------- Strategies: ConcernedParties

  get '/estrategias/partes-interesadas'            => 'concerned_parties#index', as: :concerned_parties
  get '/estrategias/partes-interesadas/nuevo'      => 'concerned_parties#new',   as: :new_concerned_party
  get '/estrategias/partes-interesadas/:id'        => 'concerned_parties#show',  as: :concerned_party
  get '/estrategias/partes-interesadas/:id/editar' => 'concerned_parties#edit',  as: :edit_concerned_party

  post  '/estrategias/partes-interesadas/nuevo'            => 'concerned_parties#create'
  patch '/estrategias/partes-interesadas/:id/editar'       => 'concerned_parties#update'
  patch '/estrategias/partes-interesadas/edit-attachments' => 'concerned_parties#edit_attachments'

  get '/estrategias/partes-interesadas/:party_id/revisiones/nueva' => 'concerned_party_revisions#new',
      as: :new_concerned_party_revision
  get '/estrategias/partes-interesadas/:party_id/revisiones/:id'   => 'concerned_party_revisions#edit',
      as: :edit_concerned_party_revision

  post  '/estrategias/partes-interesadas/:party_id/revisiones/nueva' => 'concerned_party_revisions#create'
  patch '/estrategias/partes-interesadas/:party_id/revisiones/:id'   => 'concerned_party_revisions#update'

  # -------- Strategies: Objectives

  get '/estrategias/objetivos'            => 'objectives#index', as: :objectives
  get '/estrategias/objetivos/nuevo'      => 'objectives#new',   as: :new_objective
  get '/estrategias/objetivos/:id'        => 'objectives#show',  as: :objective
  get '/estrategias/objetivos/:id/editar' => 'objectives#edit',  as: :edit_objective

  post  '/estrategias/objetivos/nuevo'             => 'objectives#create'
  patch '/estrategias/objetivos/:id/editar'        => 'objectives#update'
  patch '/estrategias/objetivos/edit-attachments' => 'objectives#edit_attachments'


  get '/estrategias/objetivos/:objective_id/revisiones/nueva' => 'objective_revisions#new',
      as: :new_objective_revision
  get '/estrategias/objetivos/:objective_id/revisiones/:id'   => 'objective_revisions#edit',
      as: :edit_objective_revision

  post  '/estrategias/objetivos/:objective_id/revisiones/nueva' => 'objective_revisions#create'
  patch '/estrategias/objetivos/:objective_id/revisiones/:id'   => 'objective_revisions#update'

  # -------- Strategies: BusinessProcesses

  get '/estrategias/procesos'            => 'business_processes#index', as: :business_processes
  get '/estrategias/procesos/nuevo'      => 'business_processes#new',   as: :new_business_process
  get '/estrategias/procesos/:id'        => 'business_processes#show',  as: :business_process
  get '/estrategias/procesos/:id/editar' => 'business_processes#edit',  as: :edit_business_process

  post  '/estrategias/procesos/nuevo'            => 'business_processes#create'
  patch '/estrategias/procesos/:id/editar'       => 'business_processes#update'
  patch '/estrategias/procesos/edit-attachments' => 'business_processes#edit_attachments'

  get '/estrategias/procesos/:process_id/revisiones/nueva' => 'business_process_revisions#new',
      as: :new_business_process_revision
  get '/estrategias/procesos/:process_id/revisiones/:id'   => 'business_process_revisions#edit',
      as: :edit_business_process_revision

  post  '/estrategias/procesos/:process_id/revisiones/nueva' => 'business_process_revisions#create'
  patch '/estrategias/procesos/:process_id/revisiones/:id'   => 'business_process_revisions#update'

  # -------- Strategies: Communications

  get '/estrategias/comunicacion'            => 'communications#index',  as: :communications
  get '/estrategias/comunicacion/nuevo'      => 'communications#new',    as: :new_communication
  get '/estrategias/comunicacion/:id'        => 'communications#show',   as: :communication
  get '/estrategias/comunicacion/:id/editar' => 'communications#edit',   as: :edit_communication

  post  '/estrategias/comunicacion/nuevo'            => 'communications#create'
  patch '/estrategias/comunicacion/:id/editar'       => 'communications#update'
  patch '/estrategias/comunicacion/edit-attachments' => 'communications#edit_attachments'


  get '/estrategias/comunicacion/:communication_id/revisiones/nueva' => 'communication_revisions#new',
      as: :new_communication_revision
  get '/estrategias/comunicacion/:communication_id/revisiones/:id'   => 'communication_revisions#edit',
      as: :edit_communication_revision

  post  '/estrategias/comunicacion/:communication_id/revisiones/nueva' => 'communication_revisions#create'
  patch '/estrategias/comunicacion/:communication_id/revisiones/:id'   => 'communication_revisions#update'

  # -------- Risks

  get '/riesgos/:type'            => 'risks#index', as: :risks
  get '/riesgos/:type/nuevo'      => 'risks#new',   as: :new_risk
  get '/riesgos/:type/:id'        => 'risks#show',  as: :risk
  get '/riesgos/:type/:id/editar' => 'risks#edit',  as: :edit_risk

  get '/riesgos/:type/:risk_id/nueva'      => 'risk_measurements#new' , as: :new_risk_measurement
  get '/riesgos/:type/:risk_id/:id/editar' => 'risk_measurements#edit', as: :edit_risk_measurement

  post  '/riesgos/:type/nuevo'         => 'risks#create'
  patch '/riesgos/:type/:id/editar/'   => 'risks#update'

  post  '/riesgos/:type/:risk_id/nueva'      => 'risk_measurements#create'
  patch '/riesgos/:type/:risk_id/:id/editar' => 'risk_measurements#update'

  # -------- Settings

app/models/objective.rb
class Objective
  include Mongoid::Document

  include EnumerableDocument
  include Referable
  include Describable

  # validates_presence_of

  embeds_one :log_book, class_name: 'Log::Book'
  before_create do
    self.log_book ||= Log::Book.new
  end

  embeds_many :revisions, class_name: 'ObjectiveRevision'

  has_many :indicators

  field :name, type: String
  field :phrase, type: String

  field :r_id, as: :responsible_id, type: BSON::ObjectId # => Person:: User

  field :lr_at, as: :last_revised_at, type: DateTime


  def new_revision(fields)
    revision = revisions.create!(fields)

    if last_revised_at.nil? || revision.revised_at > last_revised_at
      self.last_revised_at = revision.revised_at
      save!
    end

    revision
  end

  def find_revision(id)
    revisions.find(id)
  end

  def last_revision_at(format)
    last_revised_at.strftime(format) if last_revised_at
  end

  def self.display_name
    'Objetivos'
  end

  def display_name
    name
  end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  def index
    render layout: 'table'
  end

  def show
    @objective = Objective.find(params[:id])
    redirect_to_dashboard unless @objective

    render layout: 'show'
  end

  def new
    render layout: 'form'
  end

  def edit
    @objective = Objective.find(params[:id])
    redirect_to_dashboard unless @objective

    render layout: 'form'
  end

  def create
    objective = Objective.create!(objective_fields)
    log_created(objective)

    create_references(objective, references_unsafe_hash)
    add_attachments(objective, params.dig(:objective, :attachments))

    respond_to do |format|
      format.html { redirect_to(objective) }
      format.json { objective_as_json(objective) }
    end
  end

  def update
    objective = Objective.find(params[:id])
    redirect_to_dashboard && return unless objective

    objective.update!(objective_fields)
    log_edited(objective)

    create_references(objective, references_unsafe_hash)

    redirect_to objective
  end

  def edit_attachments
    objective = Objective.find(params.dig(:attachments, :element_id))
    return unless objective

    additions = params.dig(:attachments, :additions)
    removal_ids = params.dig(:attachments, :removal_ids)

    add_attachments(objective, additions) if additions
    remove_attachments(objective.class.name, objective, removal_ids) if
        removal_ids

    redirect_to objective
  end

  private

  def objective_as_json(objective)
    render json: {
      object_id: objective.id.to_s,
      object_name: objective.name
    }
  end

  def objective_fields
    fields = params.require(:objective)

    fields.permit(
      :name,
      :phrase,
      :responsible_id,
      :comments
    )
  end
end

app/views/objectives/revisions/edit.html.erb
<%= form_for(@revision, as: :revision,
             url: edit_objective_revision_path(@objective, @revision),
             method: :patch) do |f| %>

    <section class="page-content">
      <div class="page-content-inner">

        <div class="panel">

          <%= render partial: 'referables/references_nav' %>

          <div class="row form-group margin-left-50">
            <div class="col-lg-1">
              <label class="form-control-label">
                Fecha
              </label>
            </div>
            <div class="col-lg-3">
              <div class='input-group date date-picker' id='date-picker'>
                <%= text_field :raw, :revised_at, class: 'form-control',
                               data: {format: dt_form_format(true)},
                               value: DateTime.now.to_i %>
                <span class="input-group-addon">
                  <i class="icmn-calendar"></i>
                </span>
              </div>
            </div>
          </div>

          <div class="row form-group" style="margin: 30px 10px;height:400px">
            <%= f.text_area :comments, class: 'form-control', style: 'width:100%;height:300px', data: {provider: 'summernote'} %>
          </div>

          <div style="margin: 0 30px 10px 30px">
            <%= render partial: 'referables/show_all_for',
                       locals: {element: @revision, form_format: true} %>
          </div>

        </div>

      </div>
    </section>


    <!-- Confirmation modal -->
    <div id="confirmation-modal" class="modal fade modal-size-large" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content" id="confirmation-modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="confirmation-modal-title">Está Seguro?</h4>
          </div>

          <div class="modal-body" id="confirmation-modal-body">
            <%= text_area :log, :body, class: 'form-control height-150' %>
          </div>

          <div class="modal-footer">
            <div class="row">
              <div class="col-md-6 text-left">
                <button class="btn btn-danger width-150 height-50" data-dismiss="modal">Cancelar</button>
              </div>
              <div class="text-right col-md-6">
                <%= f.submit 'Ingresar', class: 'btn btn-primary width-150 height-50' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

<% content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to 'Estrategias: Objetivos', objectives_path %>
        </li>
        <li>
          <%= link_to @objective.number, objective_path(@objective) %>
        </li>
        <li>
          <span>
            Editar Revisión
          </span>
        </li>
      </ul>
    </div>
<% end %>

app/views/objectives/revisions/new.html.erb
<%= form_for(:revision, url: new_objective_revision_path(@objective)) do |f| %>

    <section class="page-content">
      <div class="page-content-inner">

        <div class="panel">

          <%= render partial: 'referables/references_nav' %>

          <div class="row form-group margin-left-50">
            <div class="col-lg-1">
              <label class="form-control-label">
                Fecha
              </label>
            </div>
            <div class="col-lg-3">
              <div class='input-group date date-picker' id='date-picker'>
                <%= text_field :raw, :revised_at, class: 'form-control',
                               data: {format: dt_form_format(true)},
                               value: DateTime.now.to_i %>
                <span class="input-group-addon">
                  <i class="icmn-calendar"></i>
                </span>
              </div>
            </div>
          </div>

          <div style="margin:50px 50px 0 50px">
            <%= f.file_field :attachments, class: 'dropify', multiple: true,
                             data: {height: '90px', width: '100%'} %>
          </div>

          <div class="row form-group" style="margin: 30px 10px;height:400px">
            <%= f.text_area :comments, class: 'form-control', style: 'width:100%;height:300px', data: {provider: 'summernote'} %>
          </div>

          <div id="references-container" style="margin: 0 30px 10px 30px">
            <h6>Referencias</h6>
          </div>

        </div>

      </div>
    </section>


    <!-- Confirmation modal -->
    <div id="confirmation-modal" class="modal fade modal-size-large" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content" id="confirmation-modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="confirmation-modal-title">Está Seguro?</h4>
          </div>

          <div class="modal-body" id="confirmation-modal-body">
            <%= text_area :log, :body, class: 'form-control height-150' %>
          </div>

          <div class="modal-footer">
            <div class="row">
              <div class="col-md-6 text-left">
                <button class="btn btn-danger width-150 height-50" data-dismiss="modal">Cancelar</button>
              </div>
              <div class="text-right col-md-6">
                <%= f.submit 'Ingresar', class: 'btn btn-primary width-150 height-50' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

<% content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to 'Estrategias: Objetivos', objectives_path %>
        </li>
        <li>
          <%= link_to @objective.number, objective_path(@objective) %>
        </li>
        <li>
          <span>
            Revisar
          </span>
        </li>
      </ul>
    </div>
<% end %>