config/routes.rb
  post  '/proveedores/fichas/nuevo'            => 'providers#create'
  patch '/proveedores/fichas/:id/editar'       => 'providers#update'
  patch '/proveedores/fichas/edit-attachments' => 'providers#edit_attachments'


  # Provider Types
  get '/proveedores/tipos'            => 'provider_types#index', as: :provider_types
  get '/proveedores/tipos/nuevo'      => 'provider_types#new',   as: :new_provider_type
  get '/proveedores/tipos/:id'        => 'provider_types#show',  as: :provider_type
  get '/proveedores/tipos/:id/editar' => 'provider_types#edit',  as: :edit_provider_type

  post  '/proveedores/tipos/nuevo'            => 'provider_types#create'
  patch '/proveedores/tipos/:id/editar'       => 'provider_types#update'
  patch '/proveedores/tipos/edit-attachments' => 'provider_types#edit_attachments'


  # Competencies & Performance evaluations
  get '/proveedores/evaluaciones/:type'       => 'provider_evaluations#index', as: :provider_evaluations
  get '/proveedores/evaluaciones/:type/nuevo' => 'provider_evaluations#new',   as: :new_provider_evaluation
  get '/proveedores/evaluaciones/:type/:id'   => 'provider_evaluations#show',  as: :provider_evaluation

  post '/proveedores/evaluaciones/:type/nuevo' => 'provider_evaluations#create'

  # -------- Analysis: Indicators

  get '/analisis/indicadores'            => 'indicators#index', as: :indicators
  get '/analisis/indicadores/nuevo'      => 'indicators#new',   as: :new_indicator
  get '/analisis/indicadores/:id'        => 'indicators#show',  as: :indicator
  get '/analisis/indicadores/:id/editar' => 'indicators#edit',  as: :edit_indicator

  get '/analisis/indicadores/:indicator_id/nueva'      => 'indicator_measurements#new' ,
      as: :new_indicator_measurement
  get '/analisis/indicadores/:indicator_id/:id/editar' => 'indicator_measurements#edit',
      as: :edit_indicator_measurement

  post  '/analisis/indicadores/nuevo'            => 'indicators#create'
  patch '/analisis/indicadores/:id/editar'       => 'indicators#update'
  patch '/analisis/indicadores/edit-attachments' => 'indicators#edit_attachments'

  post  '/analisis/indicadores/:indicator_id/nueva'      => 'indicator_measurements#create'
  patch '/analisis/indicadores/:indicator_id/:id/editar' => 'indicator_measurements#update'

  # -------- Assets

  get '/activos/:job_type'            => 'business_assets#index', as: :business_assets
  get '/activos/:job_type/nuevo'      => 'business_assets#new',   as: :new_business_asset
  get '/activos/:job_type/:id'        => 'business_assets#show',  as: :business_asset
  get '/activos/:job_type/:id/editar' => 'business_assets#edit',  as: :edit_business_asset

  get '/activos/:job_type/:asset_id/nuevo'       => 'business_asset_jobs#new',  as: :new_asset_job
  get '/activos/:job_type/:asset_id/:id/editar'  => 'business_asset_jobs#edit', as: :edit_asset_job

  post '/activos/nuevo-tipo' => 'business_assets#create_type',
       as: :new_business_asset_type

  post  '/activos/:job_type/nuevo'            => 'business_assets#create'
  patch '/activos/:job_type/:id/editar'       => 'business_assets#update'
  patch '/activos/:job_type/edit-attachments' =>  'business_assets#edit_attachments'


  post  '/activos/:job_type/:asset_id/nuevo'       => 'business_asset_jobs#create'
  patch '/activos/:job_type/:asset_id/:id/editar'  => 'business_asset_jobs#update'

  # -------- Planning

  get '/planificacion'            => 'plannings#index', as: :plannings
  get '/planificacion/nueva'      => 'plannings#new'  , as: :new_planning
  get '/planificacion/:id'        => 'plannings#show' , as: :planning
  get '/planificacion/:id/editar' => 'plannings#edit' , as: :edit_planning

  get '/planificacion/:plan_id/nueva'      => 'planning_activities#new',  as: :new_planning_activity
  get '/planificacion/:plan_id/:id/editar' => 'planning_activities#edit', as: :edit_planning_activity

  post  '/planificacion/nueva'            => 'plannings#create'
  patch '/planificacion/:id/editar'       => 'plannings#update'
  patch '/planificacion/edit-attachments' => 'plannings#edit_attachments'


  post  '/planificacion/:plan_id/nueva'      => 'planning_activities#create'
  patch '/planificacion/:plan_id/:id/editar' => 'planning_activities#update'

  # -------- Documents

  post '/documentos/reglas/nuevo' => 'rules#create', as: :new_rule

  # -- Uploads
  get '/documentos/archivos'       => 'uploaded_files#index', as: :uploaded_files
  get '/documentos/archivos/nuevo' => 'uploaded_files#new',   as: :new_uploaded_file
  get '/documentos/archivos/:id'   => 'uploaded_files#show',  as: :uploaded_file

  post '/documentos/archivos/nuevo' => 'uploaded_files#create'

  # -- Minutes

  get '/documentos/actas'            => 'minutes_folders#index', as: :minutes_folders
  get '/documentos/actas/nuevo'      => 'minutes_folders#new',   as: :new_minutes_folder
  get '/documentos/actas/:id'        => 'minutes_folders#show',  as: :minutes_folder
  get '/documentos/actas/:id/editar' => 'minutes_folders#edit',  as: :edit_minutes_folder

  post  '/documentos/actas/nuevo'      => 'minutes_folders#create'
  patch '/documentos/actas/:id/editar' => 'minutes_folders#update'

  get '/documentos/actas/:folder_id/nueva' => 'minutes#new', as: :new_minute
  get '/documentos/actas/:folder_id/:id'   => 'minutes#edit', as: :edit_minute

  post  '/documentos/actas/:folder_id/nueva' => 'minutes#create'
  patch '/documentos/actas/:folder_id/:id'   => 'minutes#update'

  # -- Definitions

  get '/documentos/definiciones'            => 'definitions#index', as: :definitions
  get '/documentos/definiciones/nuevo'      => 'definitions#new',   as: :new_definition
  get '/documentos/definiciones/:id'        => 'definitions#show',  as: :definition
  get '/documentos/definiciones/:id/editar' => 'definitions#edit',  as: :edit_definition

  post  '/documentos/definiciones/nuevo'      => 'definitions#create'
  patch '/documentos/definiciones/:id/editar' => 'definitions#update'

  # -- Questionnaires

  get '/documentos/cuestionarios'            => 'questionnaires#index', as: :questionnaires
  get '/documentos/cuestionarios/nuevo'      => 'questionnaires#new',   as: :new_questionnaire
  get '/documentos/cuestionarios/:id'        => 'questionnaires#show',  as: :questionnaire
  get '/documentos/cuestionarios/:id/editar' => 'questionnaires#edit',  as: :edit_questionnaire

  get '/documentos/cuestionarios/:id/responder' => 'questionnaires#respond',
      as: :respond_questionnaire

  post  '/documentos/cuestionarios/nuevo'      => 'questionnaires#create'
  patch '/documentos/cuestionarios/:id/editar' => 'questionnaires#update'

  post '/documentos/cuestionarios/:id/responder' => 'questionnaires#process_response'

  # -------- Strategies: SWOT

  get '/estrategias/FODA'            => 'swot#index', as: :swot_index
  get '/estrategias/FODA/nuevo'      => 'swot#new',   as: :new_swot
  get '/estrategias/FODA/:id'        => 'swot#show',  as: :swot
  get '/estrategias/FODA/:id/editar' => 'swot#edit',  as: :edit_swot

  post  '/estrategias/FODA/nuevo'      => 'swot#create'
  patch '/estrategias/FODA/:id/editar' => 'swot#update'
  patch '/estrategias/FODA/edit-attachments' => 'swot#edit_attachments'

  get '/estrategias/FODA/:swot_id/revisiones/nueva' => 'swot_revisions#new',
      as: :new_swot_revision
  get '/estrategias/FODA/:swot_id/revisiones/:id'   => 'swot_revisions#edit',
      as: :edit_swot_revision

  post  '/estrategias/FODA/:swot_id/revisiones/nueva' => 'swot_revisions#create'
  patch '/estrategias/FODA/:swot_id/revisiones/:id'   => 'swot_revisions#update'

  # -------- Strategies: PESTE

  get '/estrategias/PESTA'            => 'peste#index', as: :peste_index
  get '/estrategias/PESTA/nuevo'      => 'peste#new',   as: :new_peste
  get '/estrategias/PESTA/:id'        => 'peste#show',  as: :peste
  get '/estrategias/PESTA/:id/editar' => 'peste#edit',  as: :edit_peste

  post  '/estrategias/PESTA/nuevo'            => 'peste#create'
  patch '/estrategias/PESTA/:id/editar'       => 'peste#update'
  patch '/estrategias/PESTA/edit-attachments' => 'peste#edit_attachments'

  get '/estrategias/PESTA/:peste_id/revisiones/nueva' => 'peste_revisions#new',
      as: :new_peste_revision
  get '/estrategias/PESTA/:peste_id/revisiones/:id'   => 'peste_revisions#edit',
      as: :edit_peste_revision

  post  '/estrategias/PESTA/:peste_id/revisiones/nueva' => 'peste_revisions#create'
  patch '/estrategias/PESTA/:peste_id/revisiones/:id'   => 'peste_revisions#update'

  # -------- Strategies: ConcernedParties

  get '/estrategias/partes-interesadas'            => 'concerned_parties#index', as: :concerned_parties
  get '/estrategias/partes-interesadas/nuevo'      => 'concerned_parties#new',   as: :new_concerned_party
  get '/estrategias/partes-interesadas/:id'        => 'concerned_parties#show',  as: :concerned_party
  get '/estrategias/partes-interesadas/:id/editar' => 'concerned_parties#edit',  as: :edit_concerned_party

  post  '/estrategias/partes-interesadas/nuevo'            => 'concerned_parties#create'
  patch '/estrategias/partes-interesadas/:id/editar'       => 'concerned_parties#update'
  patch '/estrategias/partes-interesadas/edit-attachments' => 'concerned_parties#edit_attachments'

  get '/estrategias/partes-interesadas/:party_id/revisiones/nueva' => 'concerned_party_revisions#new',
      as: :new_concerned_party_revision
  get '/estrategias/partes-interesadas/:party_id/revisiones/:id'   => 'concerned_party_revisions#edit',
      as: :edit_concerned_party_revision

  post  '/estrategias/partes-interesadas/:party_id/revisiones/nueva' => 'concerned_party_revisions#create'
  patch '/estrategias/partes-interesadas/:party_id/revisiones/:id'   => 'concerned_party_revisions#update'

  # -------- Strategies: Objectives

  get '/estrategias/objetivos'            => 'objectives#index', as: :objectives
  get '/estrategias/objetivos/nuevo'      => 'objectives#new',   as: :new_objective

app/models/planning.rb
class Planning
  include Mongoid::Document

  include EnumerableDocument
  include Describable
  include Referable

  embeds_one :log_book, class_name: 'Log::Book'

  before_create do
    self.log_book ||= Log::Book.new
  end

  embeds_many :activities, class_name: 'PlanningActivity'

  field :d_at, as: :due_at, type: DateTime
  field :e_at, as: :executed_at, type: DateTime

  field :name, type: String
  field :desc, as: :description, type: String

  field :prog, as: :progress, type: Float, default: 0.0

  field :cmts, as: :comments, type: String

  def new_activity(fields)
    activities.create!(fields)

    update_progress
  end

  def find_activity(id)
    activities.find(id)
  end

  def update_progress
    self.progress = activities.avg(:progress)

    save!
  end

  def self.display_name
    'Planificación'
  end

  def display_name
    name
  end
end

app/models/planning/task.rb
class Planning::Task < Task
  include Mongoid::Document

  belongs_to :planning
end

app/models/task/planning.rb
class Task::Planning < Task
  include Mongoid::Document

  belongs_to :planning
end

app/controllers/plannings_controller.rb
class PlanningsController < ApplicationController
  def index
    render layout: 'table'
  end

  def show
    @planning = Planning.find(params[:id])
    redirect_to_dashboard unless @planning

    render layout: 'show'
  end

  def new
    render layout: 'form'
  end

  def edit
    @planning = Planning.find(params[:id])
    redirect_to_dashboard unless @planning

    render layout: 'form'
  end

  def create
    planning = Planning.create!(planning_fields)
    log_created(planning)

    create_references(planning, references_unsafe_hash)
    add_attachments(planning, params.dig(:planning, :attachments))

    respond_to do |format|
      format.html { redirect_to(planning) }
      format.json { planning_as_json(planning) }
    end
  end

  def update
    planning = Planning.find(params[:id])
    redirect_to_dashboard && return unless planning

    planning.update!(planning_fields)
    log_edited(planning)

    create_references(planning, references_unsafe_hash)

    redirect_to planning
  end

  def edit_attachments
    planning = Planning.find(params.dig(:attachments, :element_id))
    return unless planning

    additions = params.dig(:attachments, :additions)
    removal_ids = params.dig(:attachments, :removal_ids)

    add_attachments(planning, additions) if additions
    remove_attachments(planning.class.name, planning, removal_ids) if
        removal_ids

    redirect_to planning
  end

  private

  def planning_fields
    fields = params.require(:planning)

    fields[:due_at] = parse_datetime(params.dig(:raw, :due_at))

    exec = params.dig(:raw, :executed)
    fields[:executed_at] = parse_datetime(params.dig(:raw, :executed_at)) if
        exec && exec.to_i != 0

    fields.permit(
      :due_at,
      :executed_at,
      :name,
      :description,
      :comments
    )
  end

  def planning_as_json(planning)
    render json: {
      object_id: planning.id.to_s,
      object_name: planning.name
    }
  end
end

app/views/plannings/edit.html.erb
<%= form_for @planning,
             as: :planning,
             url: edit_planning_path(@planning),
             method: :patch do |f| %>

    <section class="page-content">
      <div class="page-content-inner">

        <div class="panel">
          <%= render partial: 'referables/references_nav' %>

          <div class="row form-group margin-left-50">
            <div class="col-lg-1">
              <label class="form-control-label">
                Nombre
              </label>
            </div>
            <div class="col-lg-2 margin-right-20" id="process-in">
              <%= f.text_field :name, class: 'form-control' %>
            </div>


            <div class="col-lg-1">
              <label class="form-control-label">
                Descripción
              </label>
            </div>
            <div class="col-lg-2 margin-right-20" id="process-in">
              <%= f.text_field :description, class: 'form-control' %>
            </div>

            <div class="col-lg-1">
              <label class="form-control-label">
                Fecha Planificada
              </label>
            </div>
            <div class="col-lg-2">
              <div class='input-group date date-picker' id='date-picker'>
                <%= text_field :raw, :due_at, class: 'form-control',
                               data: {format: dt_form_format(true), max: 0},
                               value: @planning.due_at.to_i %>
                <span class="input-group-addon">
                  <i class="icmn-calendar"></i>
                </span>
              </div>
            </div>
          </div>

          <div class="row form-group margin-left-50">
            <div class="col-lg-1">
              <label class="form-control-label">
                Ejecutado?
              </label>
            </div>
            <div class="col-lg-2 text-left margin-right-20">
              <%= check_box :raw, :executed, class: 'vertical-align-middle' %>
            </div>

            <div class="col-lg-1">
              <label class="form-control-label">
                Fecha Real
              </label>
            </div>
            <div class="col-lg-2">
              <div class='input-group date date-picker' id='date-picker'>
                <%= text_field :raw, :executed_at, class: 'form-control',
                               data: {format: dt_form_format(true), max: 0},
                               value: DateTime.now.to_i,
                               readonly: true %>
                <span class="input-group-addon">
                  <i class="icmn-calendar"></i>
                </span>
              </div>
            </div>
          </div>

          <div class="row form-group" style="margin: 30px 10px;height:400px">
            <%= f.text_area :comments, class: 'form-control', data: {provider: 'summernote'} %>
          </div>

          <div style="margin: 0 30px 10px 30px">
            <%= render partial: 'referables/show_all_for',
                       locals: {element: @planning, form_format: true} %>
          </div>

        </div>
      </div>
    </section>

    <!-- Confirmation modal -->
    <div id="confirmation-modal" class="modal fade modal-size-large" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content" id="confirmation-modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="confirmation-modal-title">Está Seguro?</h4>
          </div>

          <div class="modal-body" id="confirmation-modal-body">
            <%= text_area :log, :body, class: 'form-control height-150' %>
          </div>

          <div class="modal-footer">
            <div class="row">
              <div class="col-md-6 text-left">
                <button class="btn btn-danger width-150 height-50" data-dismiss="modal">Cancelar</button>
              </div>
              <div class="text-right col-md-6">
                <%= f.submit 'Ingresar', class: 'btn btn-primary width-150 height-50' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

<%= content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to plannings_path do %>
              Planificación
          <% end %>
        </li>
        <li>
          <%= link_to @planning.number, planning_path(@planning) %>
        </li>
        <li>
          <span>
            Editar Plan
          </span>
        </li>
      </ul>
    </div>
<% end %>

<%= content_for :scripts do %>
    <script>
        $('#raw_executed').click(function () {
            var execAt = $('#raw_executed_at');
            if ($(this).is(':checked')) {
                execAt.removeAttr('readonly');
            } else {
                execAt.prop('readonly', 'readonly')
            }
        });
    </script>
<% end %>

app/views/plannings/index.html.erb
<% content_for :table_name_active do %>
    Activos
<% end %>

<% content_for :table_headers do %>
    <tr>
      <th>Plan</th>
      <th>Descripción</th>
      <th>Fecha</th>
      <th>Progreso (%)</th>
    </tr>
<% end %>

<% content_for :table_body do %>
    <% plannings = Planning.order_by(due_at: :asc) %>

    <% if plannings.size != 0 %>
        <% plannings.each do |planning| %>
            <tr data-href="<%= planning_path(planning) %>">
              <td>
                <div class="expand-collapse">+</div>
                <%= planning.name %>
              </td>
              <td>
                <%= planning.description %>
              </td>
              <td>
                <%= planning.due_at.strftime(dt_rb_format(false, false)) %>
              </td>
              <td>
                <%= planning.progress || 0 %>
              </td>
            </tr>
        <% end %>
    <% else %>
        <tr>
          <td colspan="4"> No se encontraron planes.</td>
        </tr>
    <% end %>
<% end %>


<% content_for :menu do %>
    <div class="dropdown">
      <%= link_to new_planning_path, method: 'get', class: 'dropdown-inline-button' do %>
          <i class="dropdown-inline-button-icon icmn-file-plus"></i>
          Nuevo
      <% end %>
    </div>
<% end %>

<% content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
        <span>
          Planificación
        </span>
        </li>
      </ul>
    </div>
<% end %>

app/views/plannings/new.html.erb
<%= form_for(:planning, url: new_planning_path) do |f| %>

    <section class="page-content">
      <div class="page-content-inner">

        <div class="panel">
          <%= render partial: 'referables/references_nav' %>

          <div class="row form-group margin-left-50">
            <div class="col-lg-1">
              <label class="form-control-label">
                Nombre
              </label>
            </div>
            <div class="col-lg-2 margin-right-20" id="process-in">
              <%= f.text_field :name, class: 'form-control' %>
            </div>


            <div class="col-lg-1">
              <label class="form-control-label">
                Descripción
              </label>
            </div>
            <div class="col-lg-2 margin-right-20" id="process-in">
              <%= f.text_field :description, class: 'form-control' %>
            </div>

            <div class="col-lg-1">
              <label class="form-control-label">
                Fecha Planificada
              </label>
            </div>
            <div class="col-lg-2">
              <div class='input-group date date-picker' id='date-picker'>
                <%= text_field :raw, :due_at, class: 'form-control',
                               data: {format: dt_form_format(true), max: 0},
                               value: DateTime.now.to_i %>
                <span class="input-group-addon">
                <i class="icmn-calendar"></i>
              </span>
              </div>
            </div>
          </div>

          <div style="margin:50px 50px 0 50px">
            <%= f.file_field :attachments, class: 'dropify', multiple: true,
                             data: {height: '90px', width: '100%'} %>
          </div>

          <div class="row form-group" style="margin: 30px 10px;height:400px">
            <%= f.text_area :comments, class: 'form-control', data: {provider: 'summernote'}  %>
          </div>

          <div id="references-container" style="margin: 0 30px 10px 30px">
            <h6>Referencias</h6>
          </div>

        </div>
      </div>
    </section>

    <!-- Confirmation modal -->
    <div id="confirmation-modal" class="modal fade modal-size-large" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content" id="confirmation-modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="confirmation-modal-title">Está Seguro?</h4>
          </div>

          <div class="modal-body" id="confirmation-modal-body">
            <%= text_area :log, :body, class: 'form-control height-150' %>
          </div>

          <div class="modal-footer">
            <div class="row">
              <div class="col-md-6 text-left">
                <button class="btn btn-danger width-150 height-50" data-dismiss="modal">Cancelar</button>
              </div>
              <div class="text-right col-md-6">
                <%= f.submit 'Ingresar', class: 'btn btn-primary width-150 height-50' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

<%= content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to plannings_path do %>
              Planificación
          <% end %>
        </li>
        <li>
          <span>
            Nuevo
          </span>
        </li>
      </ul>
    </div>
<% end %>

app/views/plannings/show.html.erb
<%= content_for :heading_main do %>
    <div class="margin-left-50">
      <h4 class="text-capitalize">
        Progreso: <%= (@planning.progress * 100).round || 0 %>%
      </h4>
    </div>
<% end %>

<%# Populate all 3 columns of the view with keys & their values %>

<%= content_for :main_col_1 do %>
    <div class="row">
      <div class="col-lg-4 show-label">Nombre:</div>
      <div class="col-lg-8">
        <%= @planning.name %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 show-label">Descripción:</div>
      <div class="col-lg-8">
        <%= @planning.description %>
      </div>
    </div>

<% end %>

<%= content_for :main_col_2 do %>
    <div class="row">
      <div class="col-lg-4 show-label">Fecha planificada:</div>
      <div class="col-lg-8">
        <%= @planning.due_at.strftime(dt_rb_format(true, false)) %>
      </div>
    </div>
<% end %>

<%= content_for :main_col_3 do %>
    <div class="row">
      <div class="col-lg-4 show-label">Fecha real:</div>
      <div class="col-lg-8">
        <%= @planning.executed_at&.strftime(dt_rb_format(true, false)) %>
      </div>
    </div>
<% end %>

<%= content_for :extra do %>
    <% if @planning.comments? %>
        <div class="panel">
          <div class="panel-heading">
            <h5>Descripción</h5>
          </div>
          <div class="margin-left-30 margin-bottom-30">
            <%= raw @planning.comments %>
          </div>
        </div>
    <% end %>

    <div class="row is-flex">
      <div class="col-lg-5">
        <% unless @planning.attachment_ids.empty? %>
            <div class="panel padding-bottom-25">
              <%= render partial: 'uploaded_files/attachments_table',
                         locals: {element: @planning} %>
            </div>
        <% end %>
      </div>
      <div class="col-lg-1"></div>
      <div class="col-lg-6">
        <% if @planning.references? %>
            <div class="panel padding-bottom-25" style="height: 100%">
              <%= render partial: 'referables/show_all_for',
                         locals: {element: @planning} %>
            </div>
        <% end %>
      </div>
    </div>

    <% if @planning.activities? %>
        <div class="panel">
          <div class="panel-heading">
            <h5>Actividades</h5>
          </div>
          <div class="panel-body">
            <div class="row margin-left-20 margin-right-20">
              <div class="table-responsive margin-bottom-10" style="height:300px; overflow: auto">
                <table class="table">
                  <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Fecha Planificada</th>
                    <th>Progreso (%)</th>
                    <th>Fecha Real</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @planning.activities.order(due_at: :asc).each do |activity| %>

                      <tr class="activity-row" data-id="<%= activity.id %>">
                        <td>
                          <%= activity.name %>
                        </td>
                        <td>
                          <%= activity.description %>
                        </td>
                        <td>
                          <%= activity.due_at.strftime(dt_rb_format(false, false)) %>
                        </td>
                        <td>
                          <%= (activity.progress * 100).round %>
                        </td>

                        <td>
                          <%= activity.executed_at&.strftime(dt_rb_format(false, false)) %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

<%= content_for :menu do %>
    <div class="dropdown">
      <% history_content = "#{escape_javascript(render partial: 'log/modal', locals: {book: @planning.log_book})}" %>
      <a href="javascript:void(0)" class="dropdown-inline-button" onclick="showHistory('<%= history_content %>')">
        <i class="dropdown-inline-button-icon icmn-history"></i>
        Bitácora
      </a>
    </div>

    <div class="dropdown">
      <%= link_to new_planning_activity_path(@planning), method: 'get', class: 'dropdown-inline-button' do %>
          <i class="dropdown-inline-button-icon icmn-calendar"></i>
          Nueva Actividad
      <% end %>
    </div>

    <div class="dropdown">
      <%= link_to edit_planning_path(@planning), method: 'get', class: 'dropdown-inline-button' do %>
          <i class="dropdown-inline-button-icon icmn-pencil"></i>
          Editar
      <% end %>
    </div>
<% end %>

<% content_for :breadcrumbs do %>
    <div class="left">
      <ul class="list-unstyled breadcrumb breadcrumb-custom">
        <li>
          <%= link_to plannings_path do %>
              Planificación
          <% end %>
        </li>
        <li>
          <span>
            <%= @planning.number %>
          </span>
        </li>
      </ul>
    </div>
<% end %>

<%= content_for :scripts do %>
    <!-- Planning's Show Page Scripts -->
    <script type="text/javascript">
        $('.activity-row').click(function () {
            var link = '/planificacion/<%= @planning.id %>/'
                + $(this).attr('data-id') + '/editar';

            window.open(link, '_self');
        });
    </script>
<% end %>